name: runnoter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

scripts: derry.yaml

dependencies:
  flutter:
    sdk: flutter

  firebase:
    path: firebase

  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc_test: ^9.1.1
  flutter_localizations:
    sdk: flutter
  mocktail: ^0.3.0
  provider: ^6.0.5
  flutter_lints: ^2.0.1
  connectivity_plus: ^3.0.3
  rxdart: ^0.27.7
  syncfusion_flutter_charts: ^21.2.4
  collection: ^1.17.1
  intl: ^0.17.0
  syncfusion_localizations: ^21.2.5
  flutter_sticky_header: ^0.6.5
  duration_picker: ^1.1.1
  animated_splash_screen: ^1.3.0
  flutter_speed_dial: ^7.0.0
  auto_route: ^7.7.0
  get_it: ^7.6.0
  bloc_concurrency: ^0.2.2

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
