name: runnoter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

scripts: derry.yaml

dependencies:
  flutter:
    sdk: flutter

  firebase:
    path: firebase

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc_test: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  mocktail: ^0.3.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
