name: runnoter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.10.0'

scripts: derry.yaml

dependencies:
  flutter:
    sdk: flutter

  firebase:
    path: firebase

  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc_test: ^9.1.1
  flutter_localizations:
    sdk: flutter
  mocktail: ^0.3.0
  provider: ^6.0.5
  flutter_lints: ^2.0.1
  connectivity_plus: ^3.0.3
  rxdart: ^0.27.7

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
