name: firebase
description: Firebase for runnoter.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.10.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_auth_web: ^5.4.0
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
