name: firebase
description: Firebase for runnoter.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.4
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
