name: firebase
description: Firebase for runnoter.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_auth_web: ^5.4.0
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
  equatable: ^2.0.5
  connectivity_plus: ^3.0.3
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.0
  collection: ^1.17.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
