name: CI
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  flutter_analyze_syntax:
    name: Analyze syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create firebase options file
        working-directory: ./firebase/lib
        run: touch firebase_options.dart && echo "${{ secrets.FIREBASE_OPTIONS }}" > firebase_options.dart
      - name: Flutter pub get main
        run: flutter pub get
      - name: Flutter pub get firebase
        working-directory: ./firebase
        run: flutter pub get
      - name: Flutter build
        run: flutter packages pub run build_runner build
      - name: Flutter analyze
        run: flutter analyze
  flutter_test_main:
      name: Test main
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: "12.x"
        - uses: subosito/flutter-action@v2
          with:
            channel: "stable"
        - name: Create firebase options file
          working-directory: ./firebase/lib
          run: touch firebase_options.dart && echo ${{ secrets.FIREBASE_OPTIONS }} > firebase_options.dart
        - name: Flutter pub get
          run: flutter pub get
        - name: Flutter test
          run: flutter test
  flutter_test_firebase:
    name: Test firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create firebase options file
        working-directory: ./firebase/lib
        run: touch firebase_options.dart && echo ${{ secrets.FIREBASE_OPTIONS }} > firebase_options.dart
      - name: Flutter pub get
        working-directory: ./firebase
        run: flutter pub get
      - name: Flutter test
        working-directory: ./firebase
        run: flutter test
